/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./main.js",
    "./ui/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#c0c1ff",
        "on-error": "#690005",
        "error-container": "#93000a",
        "surface": "#131314",
        "surface-container": "#201f20",
        "secondary": "#c8c6c9",
        "primary": "#c0c1ff",
        "on-secondary-container": "#b6b4b8",
        "on-tertiary": "#003824",
        "tertiary-container": "#00885d",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "surface-dim": "#131314",
        "surface-container-highest": "#353436",
        "on-primary-container": "#0d0096",
        "inverse-surface": "#e5e2e3",
        "surface-bright": "#3a393a",
        "surface-container-high": "#2a2a2b",
        "surface-container-low": "#1c1b1c",
        "inverse-primary": "#494bd6",
        "on-background": "#e5e2e3",
        "on-tertiary-fixed": "#002113",
        "background": "#131314",
        "on-secondary-fixed-variant": "#47464a",
        "on-secondary": "#303033",
        "primary-fixed": "#e1e0ff",
        "on-surface-variant": "#c7c4d7",
        "on-tertiary-container": "#000703",
        "tertiary": "#4edea3",
        "outline-variant": "#464554",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#c8c6c9",
        "on-tertiary-fixed-variant": "#005236",
        "surface-variant": "#353436",
        "on-surface": "#e5e2e3",
        "on-primary": "#1000a9",
        "on-error-container": "#ffdad6",
        "secondary-container": "#47464a",
        "outline": "#908fa0",
        "surface-tint": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "primary-container": "#8083ff",
        "secondary-fixed": "#e4e1e5",
        "on-secondary-fixed": "#1b1b1e",
        "surface-container-lowest": "#0e0e0f",
        "inverse-on-surface": "#313031"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
